# Generated by Django 3.1 on 2020-08-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('era_plus', models.FloatField()),
                ('bat_ave', models.FloatField()),
                ('ops', models.FloatField()),
                ('run_diff', models.IntegerField()),
            ],
        ),
    ]
