# Generated by Django 3.1 on 2020-08-06 00:31

from django.db import migrations
from sportsreference.mlb.teams import Teams

def add_season_data(apps, schema_editor):
    Season = apps.get_model('blog', 'Season')
    summary_list = []

    for x in range(1970, 2015):
        season = str(x)
        teams = Teams(season)

        for team in teams:
            if team.abbreviation == 'ATL':
                summary_list.append((season, team.wins, team.losses, team.earned_runs_against_plus, team.batting_average, team.on_base_plus_slugging_percentage_plus, team.run_difference))
    
    summary = tuple(summary_list)
    
    Season.objects.bulk_create(Season(year=season, wins=wins, losses=losses, era_plus=era, bat_ave=batting_average, ops=ops, run_diff=run_diff) for season, wins, losses, era, batting_average, ops, run_diff in summary)

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_season'),
    ]

    operations = [
        migrations.RunPython(add_season_data)
    ]
